version: '3.8'

services:
  # Сервис приложения Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_project_app
    restart: unless-stopped
    #ports:  
    #  - "80:80" 
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    deploy: # Добавляем ограничения ресурсов
      resources:
        limits:
          cpus: '1'  # Ограничиваем использование CPU до 2 ядер
          memory: 0.9G # Ограничиваем использование памяти до 2 ГБ

  # Сервис базы данных PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: my_project_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data # Сохранение данных БД
    ports:
      - "5435:5432" # Можно убрать, если доступ к БД нужен только из контейнера app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local